name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ./update-gh-pages.sh
          echo completed
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
