name: Deploy GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          ./update-gh-pages.sh
          echo completed
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
